# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - "*"
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    pwd
    sudo apt-get install -y wget build-essential libffi-dev libgmp-dev xz-utils zlib1g-dev git gnupg libzmq3-dev libpng-dev openssl python3-setuptools libssl-dev libtinfo-dev pkg-config python-pip libfuse2
    wget -qO- https://get.haskellstack.org/ | sh
    stack build
    stack run develop luna-studio
    stack run make-package ~/luna-develop/apps/luna-studio/luna-package.yaml 2.0
  displayName: 'Run a multi-line script'
