# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - "*"

jobs:
- job: Ubuntu
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu-16.04'
  container: murbanczyk/studio-builder:latest
  variables:
    DOCKER_BUILD: "yes" # required by appimage packing tools
  steps:
  - script: |
      env
      ls -l
      stack build
      stack run develop luna-studio
      stack run make-package ~/luna-develop/apps/luna-studio/luna-package.yaml 2.0
#      cat /home/vsts/luna-develop/apps/luna-studio/build-config/backend/.stack-work/logs/zeromq4-haskell-0.7.0.log
    displayName: 'Build Linux'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: ~/luna-develop/apps/luna-studio/dist-package
      artifactName: dist
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      curl -sSL https://get.haskellstack.org/ | sh
      brew sh
      brew update
      brew install pkg-config libffi zmq
      stack build
      stack run develop luna-studio
      stack run make-package ~/luna-develop/apps/luna-studio/luna-package.yaml 2.0