# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      curl -sSL https://get.haskellstack.org/ | sh
      stack build
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      curl -sSL https://get.haskellstack.org/ | sh
      stack build
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - script: |
      curl -sS -o stack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
      7z x stack.zip -y -oC:\stack stack.exe
      set PATH=%PATH%;C:\stack
      stack build
      